"""initial schema

Revision ID: 2a099cdad91d
Revises: 
Create Date: 2026-08-15 09:35:01.698106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a099cdad91d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_muscle', sa.String(), nullable=False),
    sa.Column('movement_pattern', sa.String(), nullable=False),
    sa.Column('equipment_required', sa.String(), nullable=False),
    sa.Column('boost_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_equipment_required'), 'exercises', ['equipment_required'], unique=False)
    op.create_index(op.f('ix_exercises_primary_muscle'), 'exercises', ['primary_muscle'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('daily_boosts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_boosts_scheduled_date'), 'daily_boosts', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_daily_boosts_user_id'), 'daily_boosts', ['user_id'], unique=False)
    op.create_table('training_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_programs_user_id'), 'training_programs', ['user_id'], unique=False)
    op.create_table('swap_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_boost_id', sa.UUID(), nullable=False),
    sa.Column('new_exercise_id', sa.UUID(), nullable=False),
    sa.Column('swap_reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_boost_id'], ['daily_boosts.id'], ),
    sa.ForeignKeyConstraint(['new_exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swap_logs_user_id'), 'swap_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swap_logs_user_id'), table_name='swap_logs')
    op.drop_table('swap_logs')
    op.drop_index(op.f('ix_training_programs_user_id'), table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_index(op.f('ix_daily_boosts_user_id'), table_name='daily_boosts')
    op.drop_index(op.f('ix_daily_boosts_scheduled_date'), table_name='daily_boosts')
    op.drop_table('daily_boosts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exercises_primary_muscle'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment_required'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
